#!/bin/sh

case $# in
1) compile="$*"  ;;
0) compile="-c1" ;;
esac

EMU="/home/caerwynj/inferno64/emu/Linux/o.emu -s $compile -d"
echo $EMU
for i in t*.dis
do
	echo $i
	$EMU /dis/$i
done

echo COMMANDs
#$EMU /dis/echo.dis test1
for i in pwd ps whoami
do
	echo $i
	$EMU /dis/$i.dis
done
